# Notebook Lưu Trữ SQL Queries

Notebook này dùng để lưu trữ và chạy các câu lệnh SQL phục vụ cho các mục đích khác nhau (ví dụ: Scheduling, Monitoring...).

---

### 1. Cấu hình kết nối
Nhập module `db_connection` để dễ dàng chuyển đổi giữa các database test.

In [2]:
import db_connection
import pandas as pd

def run_query(db_num, query):
    conn = db_connection.get_connection(db_num)
    try:
        # Sử dụng pandas để hiển thị kết quả đẹp hơn dưới dạng bảng
        df = pd.read_sql_query(query, conn)
        return df
    finally:
        conn.close()

### 2. Truy vấn dữ liệu cho Task Schedule
Dưới đây là một số câu lệnh SELECT mẫu để kiểm tra trạng thái các task cần lập lịch.

#### Câu query 1: Lấy danh sách các task đang ở trạng thái 'Pending'

In [5]:
query_pending = "SELECT * FROM tasks WHERE status = 'Pending'"

print("--- Kết quả từ Database 1 ---")
display(run_query(1, query_pending))

print("\n--- Kết quả từ Database 2 ---")
display(run_query(2, query_pending))

--- Kết quả từ Database 1 ---
Connected to test_db_1.sqlite

   id     task_name    due_date   status
0   1  Daily Report  2026-04-02  Pending
1   3   Weekly Sync  2026-04-05  Pending

--- Kết quả từ Database 2 ---
Connected to test_db_2.sqlite

   id     task_name    due_date   status
0   1  Daily Report  2026-04-02  Pending
1   3   Weekly Sync  2026-04-05  Pending

#### Câu query 2: Lấy các task có hạn chót (due_date) vào ngày hôm nay hoặc sắp tới

In [3]:
query_due = "SELECT * FROM tasks WHERE due_date >= DATE('now') ORDER BY due_date ASC"

print("--- Task sắp tới từ Database 1 ---")
display(run_query(1, query_due))

--- Task sắp tới từ Database 1 ---
Connected to test_db_1.sqlite

   id        task_name    due_date     status
0   1     Daily Report  2026-04-02    Pending
1   2  Database Backup  2026-04-03  Scheduled
2   3      Weekly Sync  2026-04-05    Pending

---